### ISSUE TITLE
Running program.p4

### ISSUE THREAD

**Issue by vertcard** [JJK96/P4-filtering#3]
I am learning about P4, and exploring DDOS attack detection, could you please give instructions on how to run the program? I have used 'make run' on other P4 programs.

**Comment by JJK96** [comment]
You can compile it using`p4c`. During testing I used the `bmv2` software switch. So you might have to use the corresponding flag.

GNU Make is not a compiler, it is just a way to structure commands that should be executed. If you examine such a Makefile you should see that it is actually using `p4c` or some other compiler to compile the code. You could probably copy the necessary flags from there. 

It's been a while since I compiled p4, so I don't know everything by heart anymore. I also don't have a p4 compiler installer anymore.

**Comment by JJK96** [comment]
If you have the right compilation flags, could you PR a Makefile?
